"""Extract a pilot dataset for AeroCast from the EPA EQUATES CMAQ run (July 2019, surface
layer, a 72x72 read area - a 64x64 box plus a 4-cell ring - over central California) from
the public S3 buckets epa-equates-v1 (concentrations) and cmas-equates (meteorology).

Never downloads the source files whole: CONC3D (386 GB, netCDF3) is read through a
kerchunk-generated byte-range index into a lazy zarr/xarray view; MCIP (per-day tars, ~7 GB
each) is read by seeking to the wanted member's byte range (via a seekable s3fs file handle
and Python's tarfile) and then reading just that member's HDF5 chunks with h5netcdf.

Usage: python scripts/extract_equates_pilot.py --config configs/data/equates_2019_07_ca12km.yaml
"""
import argparse
import io
import json
import sys
import time
from pathlib import Path

import h5netcdf
import kerchunk.netCDF3 as kc3
import netCDF4
import numpy as np
import s3fs
import tarfile
import xarray as xr

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from aerocast.config import load_config  # noqa: E402
from aerocast.grid_proj import IoapiGrid  # noqa: E402

CONC_BUCKET_KEY = (
    "epa-equates-v1",
    "CMAQ_12US1/OUTPUT/CONC3D/COMBINE_CONC3D_v532_cb6r3_ae7_aq_WR413_MYR_STAGE_2019_12US1_201907.nc",
)
MCIP_TAR_TEMPLATE = (
    "cmas-equates/CMAQ_12US1/INPUT/2019/met/mcip_v51_wrf_v411_noltng/{mon:02d}/"
    "MCIPv51_WRFv411_noltng_12US1.35L.{date}.tar"
)
CONC_VARS = ["NO", "NO2", "O3", "ATOTIJ"]
MET_VARS = ["TEMP2", "WSPD10", "WDIR10", "PBL", "RGRND", "Q2"]
STATIC_VARS = ["LAT", "LON", "HT", "LWMASK"]

SOURCE_GRID = IoapiGrid(
    p_alp=33.0, p_bet=45.0, p_gam=-97.0, xcent=-97.0, ycent=40.0,
    xorig=-2556000.0, yorig=-1728000.0, xcell=12000.0, ycell=12000.0,
)


def july_days(year=2019, limit=None):
    days = [np.datetime64(f"{year}-07-{d:02d}") for d in range(1, 32)]
    return days[:limit] if limit else days


def julian(day):
    day = np.datetime64(day, "D")
    y = day.astype("datetime64[Y]")
    doy = int((day - y) / np.timedelta64(1, "D")) + 1
    year = int(str(y))
    return year * 1000 + doy


# ---------------------------------------------------------------------------
# IOAPI-style NetCDF writer
# ---------------------------------------------------------------------------

def write_ioapi_file(path, day, grid, var_units, data, extra_attrs=None):
    """data: {name: (TSTEP, LAY, ROW, COL) float32}. Writes TFLAG + variables + IOAPI attrs."""
    names = list(data.keys())
    tstep, lay, nrow, ncol = next(iter(data.values())).shape
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp.nc")
    with netCDF4.Dataset(tmp, "w", format="NETCDF4_CLASSIC") as ds:
        ds.createDimension("TSTEP", None)
        ds.createDimension("DATE-TIME", 2)
        ds.createDimension("LAY", lay)
        ds.createDimension("VAR", len(names))
        ds.createDimension("ROW", nrow)
        ds.createDimension("COL", ncol)

        sdate = julian(day)
        tflag = ds.createVariable("TFLAG", "i4", ("TSTEP", "VAR", "DATE-TIME"))
        tflag.units = "<YYYYDDD,HHMMSS>"
        tflag_vals = np.zeros((tstep, len(names), 2), dtype=np.int32)
        for t in range(tstep):
            tflag_vals[t, :, 0] = sdate
            tflag_vals[t, :, 1] = t * 10000
        tflag[:] = tflag_vals

        for name in names:
            var = ds.createVariable(name, "f4", ("TSTEP", "LAY", "ROW", "COL"), zlib=True, complevel=4)
            var.units = var_units.get(name, "")
            var.long_name = name
            var[:] = data[name]

        ds.FILEDESC = "AeroCast EQUATES pilot extract"
        ds.GDNAM = "12US1_pilot_ca"
        ds.GDTYP = 2
        ds.P_ALP, ds.P_BET, ds.P_GAM = grid.p_alp, grid.p_bet, grid.p_gam
        ds.XCENT, ds.YCENT = grid.xcent, grid.ycent
        ds.XORIG, ds.YORIG = grid.xorig, grid.yorig
        ds.XCELL, ds.YCELL = grid.xcell, grid.ycell
        ds.NCOLS, ds.NROWS, ds.NLAYS, ds.NVARS = ncol, nrow, lay, len(names)
        ds.SDATE, ds.STIME, ds.TSTEP = sdate, 0, 10000
        setattr(ds, "VAR-LIST", "".join(f"{n:<16s}" for n in names))  # matches the BAAQMD files' attribute name
        for k, v in (extra_attrs or {}).items():
            setattr(ds, k, v)
    tmp.replace(path)
    return path


# ---------------------------------------------------------------------------
# CONC3D (concentrations)
# ---------------------------------------------------------------------------

def build_conc_zarr_view(cache_path):
    bucket, key = CONC_BUCKET_KEY
    url = f"s3://{bucket}/{key}"
    if cache_path.exists():
        with open(cache_path) as f:
            refs = json.load(f)
    else:
        t0 = time.time()
        refs = kc3.NetCDF3ToZarr(url, storage_options={"anon": True}, inline_threshold=0).translate()
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        with open(cache_path, "w") as f:
            json.dump(refs, f)
        print(f"  kerchunk header parse: {time.time() - t0:.1f}s", flush=True)
    import fsspec
    fs = fsspec.filesystem("reference", fo=refs, remote_protocol="s3", remote_options={"anon": True})
    return xr.open_dataset(fs.get_mapper(""), engine="zarr", consolidated=False)


def validate_conc_subset(ds, row0, row1, col0, col1, hour_index=12):
    """Read the FULL layer-1 O3 field for one hour directly, and compare against the subset
    read for the same hour/rows/cols. Confirms the byte-range read is correct, not just fast."""
    full = ds["O3"].isel(TSTEP=hour_index, LAY=0).values  # (ROW, COL), full CONUS
    subset = ds["O3"].isel(TSTEP=hour_index, LAY=0, ROW=slice(row0, row1), COL=slice(col0, col1)).values
    expected = full[row0:row1, col0:col1]
    if not np.array_equal(subset, expected):
        raise ValueError("CONC3D subset validation FAILED: subset read does not match full-field read")
    print(f"  validation OK: subset read matches full-field read exactly (hour index {hour_index}, "
          f"{subset.size} cells, O3 range {subset.min():.3f}-{subset.max():.3f} ppbv)")


def extract_conc(cfg, grid_sub, out_dir, cache_dir, limit_days=None):
    print("=== CONC3D extraction ===", flush=True)
    box = cfg["equates"]["box"]
    row0, row1 = box["row0"] - box["ring"], box["row0"] + box["size"] + box["ring"]
    col0, col1 = box["col0"] - box["ring"], box["col0"] + box["size"] + box["ring"]

    ds = build_conc_zarr_view(cache_dir / "conc3d_refs.json")
    validate_conc_subset(ds, row0, row1, col0, col1)

    n_hours = ds.sizes["TSTEP"] - 1  # drop the trailing Aug 1 00Z record
    assert n_hours == 31 * 24, n_hours
    days = july_days(limit=limit_days)
    var_units = {}

    sub = ds[CONC_VARS].isel(TSTEP=slice(0, n_hours), LAY=0,
                              ROW=slice(row0, row1), COL=slice(col0, col1))
    for v in CONC_VARS:
        var_units[v] = str(ds[v].attrs.get("units", "")).strip()

    written = []
    for d, day in enumerate(days):
        out_path = out_dir / f"equates_conc_{str(day).replace('-', '')}.nc"
        if out_path.exists():
            written.append(out_path)
            continue
        t0 = time.time()
        day_slice = sub.isel(TSTEP=slice(d * 24, (d + 1) * 24)).load()
        data = {v: day_slice[v].values[:, None, :, :].astype(np.float32) for v in CONC_VARS}
        write_ioapi_file(out_path, day, grid_sub, var_units, data)
        written.append(out_path)
        print(f"  {day} conc -> {out_path.name} ({time.time() - t0:.1f}s)", flush=True)
    return written, var_units


# ---------------------------------------------------------------------------
# MCIP (meteorology + static)
# ---------------------------------------------------------------------------

class SubRangeFile(io.RawIOBase):
    """A read-only view of [offset, offset+size) of another seekable, readable file object."""

    def __init__(self, base, offset, size):
        self.base, self.offset, self.size, self.pos = base, offset, size, 0

    def readable(self):
        return True

    def seekable(self):
        return True

    def seek(self, pos, whence=0):
        if whence == 0:
            self.pos = pos
        elif whence == 1:
            self.pos += pos
        elif whence == 2:
            self.pos = self.size + pos
        return self.pos

    def tell(self):
        return self.pos

    def readinto(self, b):
        n = min(len(b), self.size - self.pos)
        if n <= 0:
            return 0
        self.base.seek(self.offset + self.pos)
        data = self.base.read(n)
        b[:len(data)] = data
        self.pos += len(data)
        return len(data)

    def close(self):
        pass  # the tar member's lifetime is shorter than the underlying S3 file's


def open_tar_member(fs, tar_key, member_name):
    """h5netcdf.File for one member of a tar on S3, fetching only that member's bytes
    (plus whatever h5netcdf/h5py reads on top for the variables actually accessed)."""
    base = fs.open(tar_key, "rb")
    tf = tarfile.open(fileobj=base)
    member = None
    for m in tf.getmembers():
        if m.name.endswith(member_name):
            member = m
            break
    if member is None:
        raise FileNotFoundError(f"{member_name} not found in {tar_key}")
    sub = SubRangeFile(base, member.offset_data, member.size)
    return h5netcdf.File(sub, mode="r"), base


def extract_static(fs, grid_sub, row0, row1, col0, col1, out_path):
    if out_path.exists():
        return out_path
    tar_key = MCIP_TAR_TEMPLATE.format(mon=7, date="20190701")
    h5, base = open_tar_member(fs, tar_key, "GRIDCRO2D_20190701.nc4")
    data = {}
    var_units = {}
    for v in STATIC_VARS:
        arr = np.asarray(h5.variables[v][0, 0, row0:row1, col0:col1], dtype=np.float32)
        data[v] = arr[None, None, :, :]
        var_units[v] = str(h5.variables[v].attrs.get("units", "")).strip()
    h5.close()
    base.close()
    write_ioapi_file(out_path, "2019-07-01", grid_sub, var_units, data,
                      extra_attrs={"FILEDESC": "AeroCast EQUATES pilot static fields (GRIDCRO2D subset)"})
    print(f"  static -> {out_path.name}", flush=True)
    return out_path


def extract_met(fs, cfg, grid_sub, out_dir, limit_days=None):
    print("=== MCIP meteorology extraction ===", flush=True)
    box = cfg["equates"]["box"]
    row0, row1 = box["row0"] - box["ring"], box["row0"] + box["size"] + box["ring"]
    col0, col1 = box["col0"] - box["ring"], box["col0"] + box["size"] + box["ring"]

    extract_static(fs, grid_sub, row0, row1, col0, col1, out_dir / "static.nc")

    days = july_days(limit=limit_days)
    written = []
    var_units = {}
    for day in days:
        stamp = str(day).replace("-", "")
        out_path = out_dir / f"equates_meteo_{stamp}.nc"
        if out_path.exists():
            written.append(out_path)
            continue
        t0 = time.time()
        tar_key = MCIP_TAR_TEMPLATE.format(mon=7, date=stamp)
        h5, base = open_tar_member(fs, tar_key, f"METCRO2D_{stamp}.nc4")
        data = {}
        for v in MET_VARS:
            arr = np.asarray(h5.variables[v][0:24, 0, row0:row1, col0:col1], dtype=np.float32)
            data[v] = arr[:, None, :, :]
            var_units[v] = str(h5.variables[v].attrs.get("units", "")).strip()
        h5.close()
        base.close()
        write_ioapi_file(out_path, day, grid_sub, var_units, data)
        written.append(out_path)
        print(f"  {day} meteo -> {out_path.name} ({time.time() - t0:.1f}s)", flush=True)
    return written, var_units


# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    ap.add_argument("--only", choices=["conc", "met", "both"], default="both")
    ap.add_argument("--limit-days", type=int, default=None, help="only extract the first N days of July (for testing)")
    args = ap.parse_args()

    cfg = load_config(args.config)
    eq = cfg["equates"]
    box = eq["box"]
    out_dir = Path(eq["extracted_dir"])
    cache_dir = Path(eq["cache_dir"])
    out_dir.mkdir(parents=True, exist_ok=True)
    cache_dir.mkdir(parents=True, exist_ok=True)

    new_xorig, new_yorig = SOURCE_GRID.subgrid_origin(box["row0"] - box["ring"], box["col0"] - box["ring"])
    grid_sub = IoapiGrid(SOURCE_GRID.p_alp, SOURCE_GRID.p_bet, SOURCE_GRID.p_gam,
                          SOURCE_GRID.xcent, SOURCE_GRID.ycent, new_xorig, new_yorig,
                          SOURCE_GRID.xcell, SOURCE_GRID.ycell)

    t_start = time.time()
    if args.only in ("conc", "both"):
        extract_conc(cfg, grid_sub, out_dir, cache_dir, limit_days=args.limit_days)
    if args.only in ("met", "both"):
        fs = s3fs.S3FileSystem(anon=True)
        extract_met(fs, cfg, grid_sub, out_dir, limit_days=args.limit_days)
    print(f"Done in {time.time() - t_start:.1f}s", flush=True)


if __name__ == "__main__":
    main()
